### ISSUE TITLE
Add Paul Tols color sets

### ISSUE THREAD

**Issue by kellertuer** [JuliaGraphics/NamedColors.jl#18]
There are nice colours by Paul Too that I use quite often

https://personal.sron.nl/~pault/

Is it possible to add them here, too and if so, which naming scheme would be used?

Ideas
* `tol_vibrant_blue`
* `tol_vibrantblue`
* `TolVibrantBlue`

If this is a nice Idea I can help to transcribe them (did that for myself in LaTeX already a while back using the last scheme, since LaTeX does not like underscores much).

**Comment by oxinabox** [comment]
It is possible to add them here, that would be cool.
I don't remember what naming convention, if any we follow.
You'ld have to dig about the source a bit to see.

**Comment by kellertuer** [comment]
I already saw the file format that is definetlz doable. I will go for `vibrantblue` internally then as a scheme in the file.
