### ISSUE TITLE
This project still has a REQUIRE file - should we update?

### ISSUE THREAD

**Issue by kellertuer** [JuliaGraphics/NamedColors.jl#20]
I started typing in the first few colours and wanted to test locally, but it seems in Julia 1.6 I am not able to set it to dev mode?
Should I introduce a Project.toml maybe?

**Comment by oxinabox** [comment]
yes, that would be good

**Comment by kellertuer** [comment]
Sure, then I'll do that on the same PR as with the new colours, since otherwise I can not test the well.
