### ISSUE TITLE
Add Tailwind named colors?

### ISSUE THREAD

**Issue by jmuchovej** [JuliaGraphics/NamedColors.jl#24]
👋 Maybe this is out-of-scope (since (1) the colors from Tailwind have changed multiple times over the years and (2) Tailwind is a web-framework (i.e., perhaps this opens the "add any web framework" can-of-worms?)).

Tailwind CSS has some pretty nice palettes – not necessarily for plotting, though. They document all their colors [here][colors.js] of the form `<color>.<weight>`. The `<weight>` seems rather arbitrary, but follows a general schema of... `<color>.500` is the actual target color and `weight < 500` lightens to an off-white while `weight > 500` darkens towards a dark gray (though gray doesn't dominate the color, instead the color does).

Here's a more visual representation of the palette: https://tailwindcss.com/docs/customizing-colors#default-color-palette

This would also jive really well with the namespace idea put forward in #9.

Aside: I'm up for making a PR and possibly adding a script to update these colors, but wanted to check that `NamedColors` is open to adding color sets like this before doing that.

[colors.js]: https://github.com/tailwindlabs/tailwindcss/blob/master/src/public/colors.js

**Comment by oxinabox** [comment]
I guess the key thing to check is the license on them.

**Comment by jmuchovej** [comment]
The license on the code itself is MIT  – https://github.com/tailwindlabs/tailwindcss/blob/master/LICENSE.
I _believe_ this covers the colors as well, since I don't see any licenses elsewhere, nor mention of need for licenses relating to colors.

**Comment by oxinabox** [comment]
cool, I think we could do this.
I am super busy so any review that has to wait for me would be slow.
But @kellertuer has been doing a lot more on this package lately than me, and might be able to review

**Comment by kellertuer** [comment]
Oh, I must have missed this mention somehow. I actually did not do that much on this package, but I can try to find time to review the new PR.
