### ISSUE TITLE
Great package, but you need an overview! 

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/NamedColors.jl#3]
I love this package - great stuff. Can you do the same for colormaps and gradients now? :)

But of course, you need a chart showing all the colors. This presents a few design problems, but nothing insurmountable. On A1 size paper, and with font sizes of 3 or 4 point, it's doable:

![namedcolors](https://cloud.githubusercontent.com/assets/52289/19836720/2a7e1f60-9ea1-11e6-8716-20a09e766611.png)

The PDF version is more useful, because you can zoom in and see the colors, read the text, and because it's searchable. [Here's a link](https://www.dropbox.com/s/xbe18pkahrxehog/namedcolors.pdf?dl=0) to the image as PDF.

I look forward to you adding even more colors!

(GIST for creating the chart [here](https://gist.github.com/cormullion/7f0ceddad5136914e8e1ed514a3eddf5)).

**Comment by oxinabox** [comment]
You are right.
I didn't think it was viable to make something readable.
You've shown me it is.

Your chart in really good.
I like how it handles duplicate names, and the grey gradient in the background.
Can I just link to that in the readme?

Or better yet, do you want to make a PR with the file in a docs directory,
and the gist in the proto directory, and a link to the PDF in the readme?
So you can show up in the list of contributors.
If you don't want to I can do that in a bit

Aubrey Jaffer (who made the list that most of the colors dictionaries I am using) 
put some thought into [the best way to organise colors in a chart.](http://people.csail.mit.edu/jaffer/Color/CSDR)
It would be interesting to spend some time playing with some of these space filing curves.

> I look forward to you adding even more colors!

I'm hoping to hit 8,000

**Comment by cormullion** [comment]
@oxinabox There's some cool color-sorting examples around, and the Hilbert curve one crops up often, and seems very interesting (but mathematically way above my head, sadly).

I'll have a go at a PR.
